# PRESET_BASE: interop
PRESET_BASE: mainnet # interop is only for prysm and its just a copy of mainnet with fixed fork versions
CONFIG_NAME: mokshaV2

# Transition
# ---------------------------------------------------------------
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x13c90180bf1a98db5e88deee72907db157ad5572f3ab63edcb864d5d569ad154
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0

# Genesis
# ---------------------------------------------------------------
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 10
MIN_GENESIS_TIME: 1733256000
GENESIS_DELAY: 0
GENESIS_FORK_VERSION: 0x20000089

# Forking
# ---------------------------------------------------------------
# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Bellatrix (Merge)
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092

# Deneb
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093

# Future forks
# # Electra
ELECTRA_FORK_VERSION: 0x60000038
ELECTRA_FORK_EPOCH: 18446744073709551615
# [New in Electra:EIP7251]
# 1 * 17500 * 10**9 (= 17,500,000,000,000)
# MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA: 17500000000000
MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA: 16000000000
# 2 * 35000 * 10**9 (= 70,000,000,000,000)
MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT: 70000000000000

# Misc
# ---------------------------------------------------------------
MAX_COMMITTEES_PER_SLOT: 4
TARGET_COMMITTEE_SIZE: 8
MAX_VALIDATORS_PER_COMMITTEE: 20

# Time parameters
# ---------------------------------------------------------------
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 8
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 8

# Execution
# ---------------------------------------------------------------
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Withdrawals
# ---------------------------------------------------------------
# 2**5 (= 32) validators
MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP: 32

# Validator cycle
# ---------------------------------------------------------------
MIN_PER_EPOCH_CHURN_LIMIT: 2
# 21 validators * 2 can churn per epoch = 42
CHURN_LIMIT_QUOTIENT: 42
# 17500 * 10**9 (= 17,500,000,000,000) Gwei
EJECTION_BALANCE: 17500000000000
# EJECTION_BALANCE: 16000000000

# Deposit contract (PoS)
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 14800
DEPOSIT_NETWORK_ID: 14800
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Gwei values
# ---------------------------------------------------------------
# 1000 * 10**9 (= 1,000,000,000,000) Gwei
# MIN_DEPOSIT_AMOUNT: 1000000000000
MIN_DEPOSIT_AMOUNT: 1000000000
# 35000 * 10**9 (= 35,000,000,000,000) Gwei
# Relevant after Electra fork
MIN_ACTIVATION_BALANCE: 35000000000000 
# MIN_ACTIVATION_BALANCE: 32000000000
# 35000 * 10**9 (= 35,000,000,000,000) Gwei
MAX_EFFECTIVE_BALANCE: 35000000000000
# MAX_EFFECTIVE_BALANCE: 32000000000
# 1000 * 10**9 (= 1,000,000,000,000) Gwei
EFFECTIVE_BALANCE_INCREMENT: 1000000000000
# EFFECTIVE_BALANCE_INCREMENT: 1000000000

# Reward and penalty quotients
# ---------------------------------------------------------------
BASE_REWARD_FACTOR: 38

# MAXIMUM_EFFECTIVE_BALANCE / MIN_SLASHING_PENALTY_QUOTIENT
# 35,000 / 35 = 1000 VANA token slashing penalty
MIN_SLASHING_PENALTY_QUOTIENT: 35

# Added to make lighthouse work
# Values taken from prysm mainnet configuration https://github.com/prysmaticlabs/prysm/blob/develop/config/params/mainnet_config.go#L62
# Time parameters
# ---------------------------------------------------------------
# # 12 seconds
# SECONDS_PER_SLOT: 12
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 2**11 (= 2,048) Eth1 blocks ~8 hours
ETH1_FOLLOW_DISTANCE: 2048

# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
# EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
# MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
# CHURN_LIMIT_QUOTIENT: 65536
# [New in Deneb:EIP7514] 2**3 (= 8)
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40
# 20%
REORG_HEAD_WEIGHT_THRESHOLD: 20
# 160%
REORG_PARENT_WEIGHT_THRESHOLD: 160
# `2` epochs
REORG_MAX_EPOCHS_SINCE_FINALIZATION: 2

# Added to make teku work
# Values taken from https://github.com/Consensys/teku/blob/master/ethereum/spec/src/main/resources/tech/pegasys/teku/spec/config/configs/mainnet.yaml
# Networking
# ---------------------------------------------------------------
# `10 * 2**20` (= 10485760, 10 MiB)
GOSSIP_MAX_SIZE: 10485760
# `2**10` (= 1024)
MAX_REQUEST_BLOCKS: 1024
# `2**8` (= 256)
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
# `MIN_VALIDATOR_WITHDRAWABILITY_DELAY + CHURN_LIMIT_QUOTIENT // 2` (= 33024, ~5 months)
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024
# `10 * 2**20` (=10485760, 10 MiB)
MAX_CHUNK_SIZE: 10485760
# 5s
TTFB_TIMEOUT: 5
# 10s
RESP_TIMEOUT: 10
ATTESTATION_PROPAGATION_SLOT_RANGE: 32
# 500ms
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500
MESSAGE_DOMAIN_INVALID_SNAPPY: 0x00000000
MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000
# 2 subnets per node
SUBNETS_PER_NODE: 2
# 2**8 (= 64)
ATTESTATION_SUBNET_COUNT: 64
ATTESTATION_SUBNET_EXTRA_BITS: 0
# ceillog2(ATTESTATION_SUBNET_COUNT) + ATTESTATION_SUBNET_EXTRA_BITS
ATTESTATION_SUBNET_PREFIX_BITS: 6

# Deneb
# `2**7` (=128)
MAX_REQUEST_BLOCKS_DENEB: 1024
# MAX_REQUEST_BLOCKS_DENEB * MAX_BLOBS_PER_BLOCK
MAX_REQUEST_BLOB_SIDECARS: 768
# `2**12` (= 4096 epochs, ~18 days)
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096
# `6`
BLOB_SIDECAR_SUBNET_COUNT: 6
