name: Build and Push Docker Image

on:
  push:
    branches:
      - ethstats-client  # This triggers the workflow on a push to the 'main' branch
  pull_request:
    branches:
      - ethstats-client  # Also triggers on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Get current commit SHA
        id: current_sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 2: Log in to DockerHub using the secrets
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/moksha-stats-dashboard:latest .

      # Step 4: Push the Docker image to DockerHub
      - name: Push Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/moksha-stats-dashboard:latest

